### ISSUE TITLE
how am i intended to use crafting for existing table blocks ?

### ISSUE THREAD

**Issue by Chuunkyz** [DaFuqs/Artis#10]
i added this in the config :

    "minecraft:fletching_table": {
      "type": "existing_block",
      "width": 1,
      "height": 3
    }

but now how can i make recipes with it ?

"artis:minecraft_fletching_table_shaped" and "artis:fletching_table_shaped" are both invalid

**Comment by DaFuqs** [comment]
Try simply using "minecraft:fletching_table_shaped"
