### ISSUE TITLE
Lag when using Tom's simple storages crafting terminal

### ISSUE THREAD

**Issue by DaFuqs** [DaFuqs/Artis#11]
Reported on Discord

"Apparently there is an issue with artis and Tom's simple storage. If you use the crafting terminal while artis is present, severe lag occurs. Players deleted artis.to find out this was the cause
Not sure how it happens because of this"

Mod in question: https://www.curseforge.com/minecraft/mc-mods/toms-storage

**Comment by DaFuqs** [comment]
Just using Artis and Toms Simple Storage - and a few utility mods, like REI including Chalk and Spectrum - does not seem to cause lag issues alone. Profiling via Spark did not show anything out of the ordinary (https://spark.lucko.me/OS3QcUdWPP).

@itsdinkd:
Can you get me any more information about how I can reproduce the performance issue or upload a spark profiling run with the issues, please?

**Comment by DaFuqs** [comment]
could not reproduce

**Comment by itsdinkd** [comment]
Sorry this got lost on me. I couldn't retrieve any more info, not sure how
these people came to this as the cause. If someone gives me good info I
will reply

**Comment by DaFuqs** [comment]
No problem at all. If you stumble over that issue again feel free to reopen this issue :)
