### ISSUE TITLE
[Suggestion] KubeJS Integration

### ISSUE THREAD

**Issue by Demsli** [DaFuqs/Artis#12]
KubeJS is a neat tool used in many modpacks. Using its way of writing the recipes looks a lot easier than datapacks(imo).

I tried to use KubeJS + Artis, but for some reason the NBT in the recipe is not being read. Guess it is because they are not connected.

Hopefully this suggestion is not too much to ask, but will make using the mod even better.

**Comment by Chuunkyz** [comment]
you can use event.custom() in kubejs to use datapack recipes from mods that don't "support" kubejs
also there's no nbt crafting in kubejs fabric, you have to use the NBT Crafting mod by Siphalor. you can use it with event.custom and artis

**Comment by DaFuqs** [comment]
I experienced enough KubeJS that I better not want to touch that one, honestly.
