### ISSUE TITLE
1.18.2 version crash

### ISSUE THREAD

**Issue by Monster-Zer0** [DaFuqs/Artis#17]
https://aofpaste.com/bemivazifo.yaml

happens on start

no further information unfortunately

**Comment by Monster-Zer0** [comment]
downgrading FAPI to 0.48.0 mitigated the issue.

**Comment by DaFuqs** [comment]
oh yeah, this is fixed. The newest version of Artis now works with recent FAPI. Sorry that I did not noted that earlier.
