### ISSUE TITLE
Hi, need help realizing the modification

### ISSUE THREAD

**Issue by oRma12** [DaFuqs/Artis#25]
I don't understand your documentation, to start with I spent 2 hours working on the wrong documentation at first, it's my fault I mixed it up, but the situation didn't get better, because in the old version there was support through KubeJS to do everything. Let's start with the fact that I create a script according to your methodology to change the kraft, from your documentation, let's start small, what arguments mean, "type", and others. What I can or can't enter there, what other things I can enter. I also did everything according to your tutorial, but I don't see the effect and I don't understand how to see it at all, I just copied the script, name.js. I don't understand how I can see the result and how I can understand what my options are in crypto. https://github.com/DaFuqs/Artis-Recrafted/wiki/Adding-Recipes

**Comment by DaFuqs** [comment]
No problem!

Best to take a look at the example datapacks I prepared for demonstration or testing purposes. You can find them at: https://github.com/DaFuqs/Artis-Recrafted/tree/4.0.0-1.19.2/examples (though make sure you select the correct version of Artis & Minecraft in the dropdown)
