### ISSUE TITLE
shapeless recipe's not working

### ISSUE THREAD

**Issue by Monster-Zer0** [DaFuqs/Artis#3]
is this not implemented yet?
using 

artis:table_name_shapeless

doesn't work.

unless I have to remove the key? not sure.

**Comment by DaFuqs** [comment]
The shapeless recipes are layed out a bit different from the shaped ones (similar to the vanilla crafting table).

Now that you mentioned it I noticed I never added an example for a shapeless recipe to the wiki, so here you go:
https://github.com/DaFuqs/Artis-Recrafted/wiki/Adding-Recipes

I also added that example shapeless recipe to the example data pack at https://github.com/DaFuqs/Artis-Recrafted/tree/1.18/examples
