### ISSUE TITLE
can see through blocks with default generated model

### ISSUE THREAD

**Issue by Monster-Zer0** [DaFuqs/Artis#4]
https://i.imgur.com/9tuxz6O.png

**Comment by Monster-Zer0** [comment]
for context, the table is a 5x1

it doesn't happen on 3x3's

**Comment by DaFuqs** [comment]
Can you check if your 5x1 table has "non_opaque: true" set in its config?
If not Minecraft uses culling to improve performance because it wants to decrease the amount of rendered block faces. (like if you use a texture pack to change the blocks appearance)

```
"test_table": {
  "display_name": "Test Table",
  "width": 1,
  "height": 5,
  "settings": {
	"material": "wood",
        "non_opaque": true,
	"hardness": 4,
	"resistance": 3
  },
  "tags": [
	"minecraft:blocks/needs_stone_tool",
	"minecraft:blocks/mineable/pickaxe",
  ]
},
```

I def. should document all those available settings for the "settings" key in the Wiki

**Comment by DaFuqs** [comment]
Done. Hope that helps! :)
https://github.com/DaFuqs/Artis-Recrafted/wiki/Adding-Custom-Tables#possible-entries-for-the-settings-key

**Comment by Monster-Zer0** [comment]
changing to false doesn't make a difference unfortunately.

**Comment by Monster-Zer0** [comment]
```
	    "earth_examiner": { // the block identifier, used for recipes, block states, ...
      "display_name": "Earth Examiner",
      "width": 5,
      "height": 1,
      "block_entity": true,	  // Gives your block a block entity, meaning that items will stay in the table after closing the GUI.
	  "normal_recipes": true, // Adds supports for recipes for the vanilla crafting table. Otherwise it can only craft its own recipes.
      "generate_assets": true, // Automatically generates assets for a table based on a default model.
	  "color": "#824f2b", // The GUI and table-top color (for default assets). When not included, uses default GUI colors.
      "settings": {
        "material": "dirt",
        "non_opaque": false,
        "hardness": 4,
        "resistance": 3
      },
```

**Comment by DaFuqs** [comment]
if you set "non_opaque" to false? (meaning the block is opaque)

I should really set these to true by default.

**Comment by Monster-Zer0** [comment]
Either way, you can see through it, regardless of the setting

**Comment by DaFuqs** [comment]
huh. Can you upload your complete current config please? That way I can test optimally :)

**Comment by Monster-Zer0** [comment]
https://paste.alloffabric.com/uvebetavah.json

**Comment by DaFuqs** [comment]
Okay, that took me quite a while myself tbh.

You set the material to "dirt", but "dirt" does not exist as a material. Vanilla seems to call it "soil". Changing it to soil fixes your transparency issue. You can find all available vanilla material names here: https://github.com/DaFuqs/Artis-Recrafted/blob/1.18/src/main/java/io/github/alloffabric/artis/util/BlockSettingsParser.java#L24

```
      "settings": {
        "material": "soil",
        "non_opaque": true,
        "hardness": 4,
        "resistance": 3
      },
```

Looking at the 5x1 crafting GUI I also noticed a small rendering issue with that table layout. I will release a small update today that fixes that and adds a check for non-existant materials. 👌
