### ISSUE TITLE
count doesnt work ?

### ISSUE THREAD

**Issue by Chuunkyz** [DaFuqs/Artis#7]
event.custom({
    "type": "artis:table_mega_shaped",
    "pattern": [
      "CDACCCC", "CDDABDD", "CBBABDA", "CAABAAC", "ADBABBC", "DDBADDC", "CCCCADC"
    ],
    "key": {
      "A": {"item": "spatialharvesters:base_powder"},
      "B": {"item": "kubejs:xerganite"},
      "C": {"item": "techreborn:industrial_machine_casing"},
      "D": {"item": "modern_industrialization:highly_advanced_machine_hull"}
    },
    "result": {
      "item": "spatialharvesters:casing",
      "count": 4
    }
  });

the recipe is giving me ONE casing (also latest version)

**Comment by DaFuqs** [comment]
Big oof.
At this rate instead of porting that thing creating a completely new, less buggy version would have been faster.
