### ISSUE TITLE
wrong slot and arrow color in rei

### ISSUE THREAD

**Issue by Chuunkyz** [DaFuqs/Artis#8]
![image](https://user-images.githubusercontent.com/81187289/155721924-55f724e9-2753-4324-9e31-b25823f391f6.png)

**Comment by DaFuqs** [comment]
What would be your expectation?
Can you please upload that one config entry?

**Comment by Chuunkyz** [comment]
look at the arrow and the slots, they're all grey, like if the table had no color
but like i said this is just in rei, when you use the table the color for the slots/arrow is the right one
here's the config entry but this is most likely not an issue with it, all the tables have the same issue

    "table_extreme": {
      "display_name": "Extreme Crafting Table",
      "width": 9,
      "height": 9,
      "block_entity": true,
      "generate_assets": true,
      "color": "#E18FEB",
      "settings": {
        "material": "wood",
        "non_opaque": true,
        "hardness": 4,
        "resistance": 3
      },
      "requires_tool": true,
      "tags": [
        "minecraft:blocks/needs_stone_tool",
        "minecraft:blocks/mineable/pickaxe",
      ]
    }

**Comment by DaFuqs** [comment]
![image](https://user-images.githubusercontent.com/26429514/157110715-0e876420-e730-4441-a75d-4776ae9fb587.png)

Looks good to me. Using the version of artis that I am currently uploading to CF and REI 7.1.357. If it seems to be a mod compat thing of sorts feel free to open the issue again.
